name: Update documentation in GitHub Pages

on:
  push:
    branches:
      - "4.x"
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      ! github.event.pull_request.draft &&
      ((github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]'))
    env:
      TARGET_BRANCH: gh-pages
      MAIN_BRANCH: 4.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request_target' }}
      
      - name: Checkout PR code
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set environment variables
        run: |
          echo "Setting environment variables..."
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/${{ env.MAIN_BRANCH }}" ]; then
            echo "branch=latest" >> $GITHUB_ENV
            echo "target_dir=/" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
            ref=${{ github.event.pull_request.head.ref }}
            echo "branch=${ref//\//_}" >> $GITHUB_ENV
            echo "target_dir=/branches/" >> $GITHUB_ENV
          elif [ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]; then
            ref=${{ github.ref }}
            echo "branch=${ref#refs/tags/}" >> $GITHUB_ENV
            echo "target_dir=/docs/" >> $GITHUB_ENV
          fi
          echo "branch=${{ env.branch }}"
          echo "target_dir=${{ env.target_dir }}"

      - name: Output environment variables for debugging
        run: |
          echo "Environment Variables:"
          echo "branch=${{ env.branch }}"
          echo "target_dir=${{ env.target_dir }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          yarn set version 3.7.0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build site
        run: BASE_URL=${{ env.target_dir }}${{ env.branch }}/ yarn production

      - name: Debug build output
        run: ls -lah $GITHUB_WORKSPACE/www

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Debug gh-pages content
        run: ls -lah $GITHUB_WORKSPACE/gh-pages

      - name: Tag push preparations
        if: startsWith(github.ref, 'refs/tags/')
        run: cp -a $GITHUB_WORKSPACE/www/* $GITHUB_WORKSPACE/gh-pages

      - name: Build branch docs
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/gh-pages${{ env.target_dir }}" ]; then mkdir -p $GITHUB_WORKSPACE/gh-pages${{ env.target_dir }} ; fi
          rm -rf $GITHUB_WORKSPACE/gh-pages${{ env.target_dir }}${{ env.branch }}
          mv $GITHUB_WORKSPACE/www/ $GITHUB_WORKSPACE/gh-pages${{ env.target_dir }}${{ env.branch }}

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ env.TARGET_BRANCH }}
          folder: gh-pages
